### ISSUE TITLE
WP1 T1.3 "Community Engagement Panel"

### ISSUE THREAD

**Issue by annefou** [minrk/horizon-widera-2022#4]
What is the respective role of each partner in WP1 T1.3? 

- What is "regular community engagement panel meetings"? once a year? Is it linked to any event we would organize? 
- How efforts will be coordinated with WP5?
- How do we measure the effectiveness of this Task?

**Comment by fangohr** [comment]
- The details are described in the task. 
- I'd expect that PIs and staff working on WP5 (probably all of us) join the meeting with the CEP.
- I would have hoped we do not need to describe how we measure the effectiveness of each task.

**Comment by fangohr** [comment]
Please reopen if this doesn't answer it.
