### ISSUE TITLE
WP5 tasks and overall objective of the WP

### ISSUE THREAD

**Issue by annefou** [minrk/horizon-widera-2022#6]
- From what I understand the goal of this WP is a bit more than dissemination of the results of this project, right?
- Is there any plan activities (dissemination/outreach) towards "people" who develop and deploy services? For instance, towards EOSC "service providers" to make sure there is no delay between what you make available and what is available to researchers via EOSC.
- For training: is there a need to better specify (and differentiate) training towards researchers, RSEs or other support staff?
- For outreach and communication: Is there anything towards more "high-level" academic staff (such as professors) and policy makers?

**Comment by fangohr** [comment]
Hi @annefou, thank you for engaging. What you see is my first attempt to proposal a reasonable set of objectives and tasks - taking into account what I have gathered from discussions what you and we want to and may be able to deliver. 

By all means extend and modify this as you think is good. 

We should get together soon to discuss in person.

**Comment by fangohr** [comment]
These are good ideas! 

The "training for service providers" should be mentioned I think, and mentioning the differentiated training options for different target groups is also good.

Can you check if any of those may be covered already in the description of the tasks of WP5, and potentially modify the tasks (or add one more) to integrate your ideas?

**Comment by fangohr** [comment]
Regarding 'high-level' or 'senior' academics or those caught up in administrative tasks. This is an interesting and complicated point. 

In many ways, they should be persuaded of the importance of reproducible and open science by the same arguments we use for more junior researchers.

Maybe we can try to use our connection to publishers and research funders (via CEP) to push for policies that - in turn - motivate more senior academics to give a higher priority to this topics in their running of the universities?

**Comment by annefou** [comment]
> Maybe we can try to use our connection to publishers and research funders (via CEP) to push for policies that - in turn - motivate more senior academics to give a higher priority to this topics in their running of the universities?

Yes.  You are right. This is the role of the CEP. When I wrote this issue many things were not clear to me in the proposal. We can probably close this issue (I will go through WP5).
